# Author:  		Jude de Villiers
# Origin:  		E&E Engineering - Stellenbosch University
# For:					Supertools, Coldflux Project - IARPA
# Created: 		2019-05-09
# Modified:
# license:
# Description: Configuration file for defining stuffs
# File:				 config.toml

[File_Locations]
	defFileName = "./data/USC_new/KSA4_route.def"
	cirFileName = "./data/USC_new/KSA4_routeNEW.cir"	# output file name
	dotFileName = ""

[Parameters]
	fix_PTL_length = 10000.0 			# -1: No modification of tracks/PTLs; 0>= sets a fixed track length

[NETLIST_LOCATIONS]
	LSmitll_AND2T   = "data/cell_lib/RSFQ_LS_MITLL_1_4/LSmitll_AND2T.cir"
	LSmitll_DCSFQ   = "data/cell_lib/RSFQ_LS_MITLL_1_4/LSmitll_DCSFQ.cir"
	LSmitll_DFFT    = "data/cell_lib/RSFQ_LS_MITLL_1_4/LSmitll_DFFT.cir"
	LSmitll_MERGET  = "data/cell_lib/RSFQ_LS_MITLL_1_4/LSmitll_MERGET.cir"
	LSmitll_NOTT    = "data/cell_lib/RSFQ_LS_MITLL_1_4/LSmitll_NOTT.cir"
	LSmitll_OR2T    = "data/cell_lib/RSFQ_LS_MITLL_1_4/LSmitll_OR2T.cir"
	LSmitll_SPLITT  = "data/cell_lib/RSFQ_LS_MITLL_1_4/LSmitll_SPLITT.cir"
	LSmitll_XORT    = "data/cell_lib/RSFQ_LS_MITLL_1_4/LSmitll_XORT.cir"
	LSmitll_JTLT    =	"data/cell_lib/RSFQ_LS_MITLL_1_4/LSmitll_jtlt.cir"
	LSmitll_NDROT  =	"data/cell_lib/RSFQ_LS_MITLL_1_4/LSmitll_NDROT.cir"
# The arrays shows the pins of the cells for the SPICE sub-circuits.
# The order of the pins/ports are important due to mapping
[LSmitll_netlist]
	LSmitll_AND2T   = ["a", "b", "clk", "q"]
	LSmitll_DCSFQ   = ["a", "q"]
	LSmitll_DFFT    = ["a", "clk", "q"]
	LSmitll_JTLT   	= ["a", "q"]
	LSmitll_MERGET  = ["a", "b", "q"]
	LSmitll_NDROT   = ["a", "b", "clk", "q"] # a - IN_SET; b - IN_RESET
	LSmitll_NOTT    = ["a", "clk", "q"]
	LSmitll_OR2T    = ["a", "b", "clk", "q"]
	LSmitll_SPLITT  = ["a", "q", "r"]
	LSmitll_XORT    = ["a", "b", "clk", "q"]
	PAD             = ["P1"]								# does NOT EXIST, used for mapping in/out pins

# Basic translator for USC to LSMITLL. Used in JoSIM
[USC2LSmitll]
	# Components
	JTLT = "LSmitll_JTLT"
	MERGET = "LSmitll_MERGET"
	SPLIT = "LSmitll_SPLITT"
	DFF = "LSmitll_DFFT"
	NOTT = "LSmitll_NOTT"
	AND2T = "LSmitll_AND2T"
	OR2T = "LSmitll_OR2T"
	XOR2T = "LSmitll_XORT"
	PAD = "PAD"

	# Pins
	INOUT_1 = "P1" # just for pads
	IN_1 = "a"
	IN_2 = "b"
	OUT_1 = "q"
	OUT_2 = "r"
	CLK = "clk"

# The arrays shows the names of the pins of the macros(cells) for in the LEF/DEF file.
# [USC_LEF]
# 	PAD       = ["P1"]
# 	AND2      = ["IN_A", "IN_B", "OUT_OUT", "IN_CLK", "OUT_CLK"]
# 	XOR2a     = ["IN_A", "IN_B", "OUT_OUT", "IN_CLK", "OUT_CLK"]
# 	OR2       = ["IN_A", "IN_B", "OUT_OUT", "IN_CLK", "OUT_CLK"]
# 	NOT       = ["IN_A", "OUT_OUT", "IN_CLK", "OUT_CLK"]
# 	DFF       = ["IN_SET", "OUT_OUT", "IN_CLK", "OUT_CLK"]
# 	MUX21     = ["IN_A", "IN_SEL", "IN_B", "OUT_OUT", "IN_CLK", "OUT_CLK"]
# 	NDRO      = ["IN_SET", "OUT_OUT", "IN_CLK", "OUT_CLK"]
# 	SPLITTER  = ["IN_IN", "OUT_OUT1", "OUT_OUT2", "IN_CLK", "OUT_CLK"]
# 	Merge     = ["IN_A", "IN_B", "OUT_OUT", "IN_CLK", "OUT_CLK"]
# 	SPLITCLK0 = ["IN_CLK", "OUT_CLK1", "OUT_CLK2"]
# 	SPLITCLK1 = ["IN_CLK", "OUT_CLK1", "OUT_CLK2"]
# 	SPLITCLK2 = ["IN_CLK", "OUT_CLK1", "OUT_CLK2"]
# 	SPLITCLK3 = ["IN_CLK", "OUT_CLK1", "OUT_CLK2"]
# 	SPLITCLK4 = ["IN_CLK", "OUT_CLK1", "OUT_CLK2"]
# 	SPLITCLK5 = ["IN_CLK", "OUT_CLK1", "OUT_CLK2"]
# 	SPLITCLK6 = ["IN_CLK", "OUT_CLK1", "OUT_CLK2"]
# 	SPLITCLK7 = ["IN_CLK", "OUT_CLK1", "OUT_CLK2"]