# Author:  		Jude de Villiers
# Origin:  		E&E Engineering - Stellenbosch University
# For:					Supertools, Coldflux Project - IARPA
# Created: 		2019-05-09
# Modified:
# license:
# Description: Configuration file for defining stuffs
# File:				 config.toml

# version = 0.3

# Optional run parameters which can be utilised instead of CLI parameters
[run_parameters]
	# current possible commands: gds; josim; decipherer
	Command     = "josim"

	# outFileName = "data/results/JoSIM_HASH_KSA4_route_opt.cir"

	# ----------------------------------------------------------------------------
	# --------------------------------- SUN --------------------------------------
	# ----------------------------------------------------------------------------

	lefFileName = "data/lefdef/SUN/lef_2_metals.lef"

	# Kogge-Stone adders
	defFileName = "data/lefdef/SUN/KSA4_route.def"
	# defFileName = "data/lefdef/SUN/KSA8_route.def"
	# defFileName = "data/lefdef/SUN/KSA16_route.def"
	# defFileName = "data/lefdef/SUN/KSA32_route.def"

	# Array multipliers
	# defFileName = "data/lefdef/SUN/arrmult4_route.def"
	# defFileName = "data/lefdef/SUN/arrmult8_route.def"

	# Integer divider
	# defFileName = "data/lefdef/SUN/ID4s_route.def"

	# ISCAS85 (benchmark circuit)
	# defFileName = "data/lefdef/SUN/c432_route.def"
	# defFileName = "data/lefdef/SUN/c499_route.def"
	# defFileName = "data/lefdef/SUN/c880_route.def"
	# defFileName = "data/lefdef/SUN/c1355_route.def"
	# defFileName = "data/lefdef/SUN/c1908_route.def"

	# ----------------------------------------------------------------------------
	# --------------------------------- USC --------------------------------------
	# ----------------------------------------------------------------------------

	# lefFileName = "data/lefdef/USC/lef_2_metals.lef"

	# Kogge-Stone adders
	# defFileName = "data/lefdef/USC/KSA4_route_opt.def"
	# defFileName = "data/lefdef/USC/KSA8_route_opt.def"
	# defFileName = "data/lefdef/USC/KSA16_route_opt.def"
	# defFileName = "data/lefdef/USC/KSA32_route_opt.def"

	# Array multipliers
	# defFileName = "data/lefdef/USC/arrmult4_route_opt.def"
	# defFileName = "data/lefdef/USC/arrmult8_route_opt.def"
	# defFileName = "data/lefdef/USC/arrmult16_placed_route_opt.def"

	# Integer divider
	# defFileName = "data/lefdef/USC/ID4s_route_opt.def"
	# defFileName = "data/lefdef/USC/ID8s_route_opt.def"
	# defFileName = "data/lefdef/USC/ID16s_route_opt.def"

[NETLIST_LOCATIONS]
	LSMITLL_AND2T   = "data/cell_lib/LSmitll/LSMITLL_AND2T.subcir"
	LSmitll_DCSFQ   = "data/cell_lib/LSmitll/LSMITLL_DCSFQ.subcir"
	LSMITLL_DFFT    = "data/cell_lib/LSmitll/LSMITLL_DFFT.subcir"
	LSmitll_MERGET  = "data/cell_lib/LSmitll/LSMITLL_MERGET.subcir"
	LSMITLL_NOTT    = "data/cell_lib/LSmitll/LSMITLL_NOTT.subcir"
	LSMITLL_OR2T    = "data/cell_lib/LSmitll/LSMITLL_OR2T.subcir"
	MITLL_SPLITT    = "data/cell_lib/LSmitll/LSMITLL_SPLITT.subcir"
	LSMITLL_XORT    = "data/cell_lib/LSmitll/LSMITLL_XORT.subcir"
	# LSmitll_SFQDC1  =
	# LSMITLL_JTLT    =
	# LSMITLL_NDROT   =
	# "data/cell_lib/LSmitll/LSMITLL_PTLTX.subcir"
	# "data/cell_lib/LSmitll/LSMITLL_DCSFQ.subcir"
	# "data/cell_lib/LSmitll/LSMITLL_PTLRX.subcir"

# The arrays shows the pins of the cells for the SPICE sub-circuits.
# The order of the pins/ports are important due to mapping
[LSmitll_netlist]
	LSMITLL_AND2T   = ["IN_CLK", "IN_1", "IN_2", "OUT"]
	LSmitll_DCSFQ   = ["IN", "OUT"]
	LSMITLL_DFFT    = ["IN", "IN_CLK", "OUT"]
	LSMITLL_JTLT    = ["IN", "OUT"]
	LSmitll_MERGET  = ["IN_1", "IN_2", "OUT"]
	LSMITLL_NDROT   = ["IN_SET", "IN_RESET", "IN_CLK", "OUT"]
	LSMITLL_NOTT    = ["IN", "IN_CLK", "OUT"]
	LSMITLL_OR2T    = ["IN_CLK", "IN_1", "IN_2", "OUT"]
	LSmitll_SFQDC1  = ["IN", "OUT"]
	MITLL_SPLITT    = ["IN", "OUT_1", "OUT_2"]
	LSMITLL_XORT    = ["IN_CLK", "IN_1", "IN_2", "OUT"]
	PAD             = ["P1"]																		# does NOT EXIST, used for mapping in/out pins

# Basic translator for USC to LSMITLL. Used in JoSIM
[USC2LSmitll]
	AND2T     = "LSMITLL_AND2T"
	# DCSFQT  = "LSmitll_DCSFQ"
	DFFT      = "LSMITLL_DFFT"
	JTLT      = "LSMITLL_JTLT"
	Merge     = "LSmitll_MERGET"
	# NDROT   = "LSMITLL_NDROT"
	NOTT      = "LSMITLL_NOTT"
	OR2T      = "LSMITLL_OR2T"
	# SFQDCT  = "LSmitll_SFQDC1"
	XOR2T     = "LSMITLL_XORT"
	SPLITT    = "MITLL_SPLITT"
	SPLITCLK0 = "MITLL_SPLITT"
	SPLITCLK1 = "MITLL_SPLITT"
	SPLITCLK2 = "MITLL_SPLITT"
	SPLITCLK3 = "MITLL_SPLITT"
	SPLITCLK4 = "MITLL_SPLITT"
	SPLITCLK5 = "MITLL_SPLITT"
	SPLITCLK6 = "MITLL_SPLITT"
	SPLITCLK7 = "MITLL_SPLITT"
	PAD       = "PAD"
	P1        = "P1"
	IN_CLK    = "IN_CLK"
	CLK    = "IN_CLK"
	IN1      = "IN_1"
	IN2      = "IN_2"
	IN     = "IN"
	OUT   = "OUT"
	OUT_CLK   = "??"
	IN_CLK_S  = "IN"
	OUT1  = "OUT_1"
	OUT2  = "OUT_2"
	OUT_CLK1  = "OUT_1"
	OUT_CLK2  = "OUT_2"
	IN_SET    = "IN"

# The arrays shows the names of the pins of the macros(cells) for in the LEF/DEF file.
[USC_LEF]
	PAD       = ["P1"]
	AND2      = ["IN_A", "IN_B", "OUT_OUT", "IN_CLK", "OUT_CLK"]
	XOR2a     = ["IN_A", "IN_B", "OUT_OUT", "IN_CLK", "OUT_CLK"]
	OR2       = ["IN_A", "IN_B", "OUT_OUT", "IN_CLK", "OUT_CLK"]
	NOT       = ["IN_A", "OUT_OUT", "IN_CLK", "OUT_CLK"]
	DFF       = ["IN_SET", "OUT_OUT", "IN_CLK", "OUT_CLK"]
	MUX21     = ["IN_A", "IN_SEL", "IN_B", "OUT_OUT", "IN_CLK", "OUT_CLK"]
	NDRO      = ["IN_SET", "OUT_OUT", "IN_CLK", "OUT_CLK"]
	SPLITTER  = ["IN_IN", "OUT_OUT1", "OUT_OUT2", "IN_CLK", "OUT_CLK"]
	Merge     = ["IN_A", "IN_B", "OUT_OUT", "IN_CLK", "OUT_CLK"]
	SPLITCLK0 = ["IN_CLK", "OUT_CLK1", "OUT_CLK2"]
	SPLITCLK1 = ["IN_CLK", "OUT_CLK1", "OUT_CLK2"]
	SPLITCLK2 = ["IN_CLK", "OUT_CLK1", "OUT_CLK2"]
	SPLITCLK3 = ["IN_CLK", "OUT_CLK1", "OUT_CLK2"]
	SPLITCLK4 = ["IN_CLK", "OUT_CLK1", "OUT_CLK2"]
	SPLITCLK5 = ["IN_CLK", "OUT_CLK1", "OUT_CLK2"]
	SPLITCLK6 = ["IN_CLK", "OUT_CLK1", "OUT_CLK2"]
	SPLITCLK7 = ["IN_CLK", "OUT_CLK1", "OUT_CLK2"]